// Code generated by go-swagger; DO NOT EDIT.

package template_set

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/checkr/openmock/swagger_gen/models"
)

// NewPostTemplateSetParams creates a new PostTemplateSetParams object
// no default values defined in spec.
func NewPostTemplateSetParams() PostTemplateSetParams {

	return PostTemplateSetParams{}
}

// PostTemplateSetParams contains all the bound params for the post template set operation
// typically these are obtained from a http.Request
//
// swagger:parameters postTemplateSet
type PostTemplateSetParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*mocks to add
	  Required: true
	  In: body
	*/
	Mocks models.Mocks
	/*set key to create
	  Required: true
	  In: path
	*/
	SetKey string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostTemplateSetParams() beforehand.
func (o *PostTemplateSetParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Mocks
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("mocks", "body"))
			} else {
				res = append(res, errors.NewParseError("mocks", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Mocks = body
			}
		}
	} else {
		res = append(res, errors.Required("mocks", "body"))
	}
	rSetKey, rhkSetKey, _ := route.Params.GetOK("setKey")
	if err := o.bindSetKey(rSetKey, rhkSetKey, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindSetKey binds and validates parameter SetKey from path.
func (o *PostTemplateSetParams) bindSetKey(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.SetKey = raw

	return nil
}
