// Code generated by go-swagger; DO NOT EDIT.

package template_set

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostTemplateSetHandlerFunc turns a function with the right signature into a post template set handler
type PostTemplateSetHandlerFunc func(PostTemplateSetParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostTemplateSetHandlerFunc) Handle(params PostTemplateSetParams) middleware.Responder {
	return fn(params)
}

// PostTemplateSetHandler interface for that can handle valid post template set params
type PostTemplateSetHandler interface {
	Handle(PostTemplateSetParams) middleware.Responder
}

// NewPostTemplateSet creates a new http.Handler for the post template set operation
func NewPostTemplateSet(ctx *middleware.Context, handler PostTemplateSetHandler) *PostTemplateSet {
	return &PostTemplateSet{Context: ctx, Handler: handler}
}

/*PostTemplateSet swagger:route POST /template_sets/{setKey} template_set postTemplateSet

creates / overrides the template set with setKey to the body contents

*/
type PostTemplateSet struct {
	Context *middleware.Context
	Handler PostTemplateSetHandler
}

func (o *PostTemplateSet) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostTemplateSetParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
