// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// ActionSleep pause the action thread for a time
// swagger:model ActionSleep
type ActionSleep struct {

	// time to wait in seconds; e.g. '1s'
	Duration string `json:"duration,omitempty"`
}

// Validate validates this action sleep
func (m *ActionSleep) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ActionSleep) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ActionSleep) UnmarshalBinary(b []byte) error {
	var res ActionSleep
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
