// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ActionPublishAMQP publish a message on AMQP if this behaviors condition is met
// swagger:model ActionPublishAMQP
type ActionPublishAMQP struct {

	// TODO
	// Required: true
	Exchange *string `json:"exchange"`

	// string payload to send on AMQP
	Payload string `json:"payload,omitempty"`

	// file name (relative to working directory of OM) to load HTTP body from
	PayloadFromFile string `json:"payload_from_file,omitempty"`

	// TODO
	// Required: true
	RoutingKey *string `json:"routing_key"`
}

// Validate validates this action publish a m q p
func (m *ActionPublishAMQP) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateExchange(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRoutingKey(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ActionPublishAMQP) validateExchange(formats strfmt.Registry) error {

	if err := validate.Required("exchange", "body", m.Exchange); err != nil {
		return err
	}

	return nil
}

func (m *ActionPublishAMQP) validateRoutingKey(formats strfmt.Registry) error {

	if err := validate.Required("routing_key", "body", m.RoutingKey); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ActionPublishAMQP) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ActionPublishAMQP) UnmarshalBinary(b []byte) error {
	var res ActionPublishAMQP
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
