// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// ActionReplyHTTP reply to incoming HTTP that triggered this behavior with a response
// swagger:model ActionReplyHTTP
type ActionReplyHTTP struct {

	// Text body to send over HTTP, can use templating
	Body string `json:"body,omitempty"`

	// file name (relative to working directory of OM) to load HTTP body from
	BodyFromFile string `json:"body_from_file,omitempty"`

	// map of string to string specifying HTTP headers to attach to our message
	Headers interface{} `json:"headers,omitempty"`

	// HTTP status code to reply with
	StatusCode *int64 `json:"status_code,omitempty"`
}

// Validate validates this action reply HTTP
func (m *ActionReplyHTTP) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ActionReplyHTTP) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ActionReplyHTTP) UnmarshalBinary(b []byte) error {
	var res ActionReplyHTTP
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
