// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ActionSleep pause the action thread for a time
// swagger:model ActionSleep
type ActionSleep struct {

	// time to wait in seconds; e.g. '1s'
	// Required: true
	// Pattern: [\d+]s
	Duration *string `json:"duration"`
}

// Validate validates this action sleep
func (m *ActionSleep) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDuration(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ActionSleep) validateDuration(formats strfmt.Registry) error {

	if err := validate.Required("duration", "body", m.Duration); err != nil {
		return err
	}

	if err := validate.Pattern("duration", "body", string(*m.Duration), `[\d+]s`); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ActionSleep) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ActionSleep) UnmarshalBinary(b []byte) error {
	var res ActionSleep
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
