// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ExpectAMQP expect a m q p
// swagger:model ExpectAMQP
type ExpectAMQP struct {

	// TODO
	// Required: true
	Exchange *string `json:"exchange"`

	// TODO
	// Required: true
	Queue *string `json:"queue"`

	// TODO
	// Required: true
	RoutingKey *string `json:"routing_key"`
}

// Validate validates this expect a m q p
func (m *ExpectAMQP) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateExchange(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateQueue(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRoutingKey(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ExpectAMQP) validateExchange(formats strfmt.Registry) error {

	if err := validate.Required("exchange", "body", m.Exchange); err != nil {
		return err
	}

	return nil
}

func (m *ExpectAMQP) validateQueue(formats strfmt.Registry) error {

	if err := validate.Required("queue", "body", m.Queue); err != nil {
		return err
	}

	return nil
}

func (m *ExpectAMQP) validateRoutingKey(formats strfmt.Registry) error {

	if err := validate.Required("routing_key", "body", m.RoutingKey); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ExpectAMQP) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ExpectAMQP) UnmarshalBinary(b []byte) error {
	var res ExpectAMQP
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
