// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ExpectGRPC expect g RPC
//
// swagger:model ExpectGRPC
type ExpectGRPC struct {

	// GRPC method to expect to trigger this behavior
	Method string `json:"method,omitempty"`

	// GRPC service to expect to trigger this behavior
	Service string `json:"service,omitempty"`
}

// Validate validates this expect g RPC
func (m *ExpectGRPC) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ExpectGRPC) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ExpectGRPC) UnmarshalBinary(b []byte) error {
	var res ExpectGRPC
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
