// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PublishKafkaActionPerformed kafka reply info that would be replied when an evaluated mock did PublishKafka action
//
// swagger:model PublishKafkaActionPerformed
type PublishKafkaActionPerformed struct {

	// rendered payload
	Payload string `json:"payload,omitempty"`

	// the kafka topic to send to
	Topic string `json:"topic,omitempty"`
}

// Validate validates this publish kafka action performed
func (m *PublishKafkaActionPerformed) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PublishKafkaActionPerformed) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PublishKafkaActionPerformed) UnmarshalBinary(b []byte) error {
	var res PublishKafkaActionPerformed
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
