// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ReplyHTTPActionPerformed http info that would be replied when an evaluated mock did ReplyHTTP action
//
// swagger:model ReplyHTTPActionPerformed
type ReplyHTTPActionPerformed struct {

	// body bytes-converted-to-string returned in HTTP reply
	Body string `json:"body,omitempty"`

	// the HTTP content-type of the reply
	ContentType string `json:"content_type,omitempty"`

	// Key-value pair HTTP headers attached to the reply
	Headers interface{} `json:"headers,omitempty"`

	// HTTP status code in the reply
	StatusCode string `json:"status_code,omitempty"`
}

// Validate validates this reply HTTP action performed
func (m *ReplyHTTPActionPerformed) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ReplyHTTPActionPerformed) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ReplyHTTPActionPerformed) UnmarshalBinary(b []byte) error {
	var res ReplyHTTPActionPerformed
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
