// Code generated by go-swagger; DO NOT EDIT.

package template

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteTemplateParams creates a new DeleteTemplateParams object
// no default values defined in spec.
func NewDeleteTemplateParams() DeleteTemplateParams {

	return DeleteTemplateParams{}
}

// DeleteTemplateParams contains all the bound params for the delete template operation
// typically these are obtained from a http.Request
//
// swagger:parameters deleteTemplate
type DeleteTemplateParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*key of template to delete
	  Required: true
	  In: path
	*/
	TemplateKey string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewDeleteTemplateParams() beforehand.
func (o *DeleteTemplateParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rTemplateKey, rhkTemplateKey, _ := route.Params.GetOK("templateKey")
	if err := o.bindTemplateKey(rTemplateKey, rhkTemplateKey, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindTemplateKey binds and validates parameter TemplateKey from path.
func (o *DeleteTemplateParams) bindTemplateKey(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.TemplateKey = raw

	return nil
}
