// Code generated by go-swagger; DO NOT EDIT.

package template

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteTemplatesHandlerFunc turns a function with the right signature into a delete templates handler
type DeleteTemplatesHandlerFunc func(DeleteTemplatesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteTemplatesHandlerFunc) Handle(params DeleteTemplatesParams) middleware.Responder {
	return fn(params)
}

// DeleteTemplatesHandler interface for that can handle valid delete templates params
type DeleteTemplatesHandler interface {
	Handle(DeleteTemplatesParams) middleware.Responder
}

// NewDeleteTemplates creates a new http.Handler for the delete templates operation
func NewDeleteTemplates(ctx *middleware.Context, handler DeleteTemplatesHandler) *DeleteTemplates {
	return &DeleteTemplates{Context: ctx, Handler: handler}
}

/*DeleteTemplates swagger:route DELETE /templates template deleteTemplates

Deletes any templates that have been added to the admin endpoint (without a setKey)

*/
type DeleteTemplates struct {
	Context *middleware.Context
	Handler DeleteTemplatesHandler
}

func (o *DeleteTemplates) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteTemplatesParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
