// Code generated by go-swagger; DO NOT EDIT.

package template

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	models "github.com/checkr/openmock/swagger_gen/models"
)

// NewPostTemplatesParams creates a new PostTemplatesParams object
// no default values defined in spec.
func NewPostTemplatesParams() PostTemplatesParams {

	return PostTemplatesParams{}
}

// PostTemplatesParams contains all the bound params for the post templates operation
// typically these are obtained from a http.Request
//
// swagger:parameters postTemplates
type PostTemplatesParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*mocks to add
	  Required: true
	  In: body
	*/
	Mocks models.Mocks
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostTemplatesParams() beforehand.
func (o *PostTemplatesParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Mocks
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("mocks", "body"))
			} else {
				res = append(res, errors.NewParseError("mocks", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Mocks = body
			}
		}
	} else {
		res = append(res, errors.Required("mocks", "body"))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
