// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi OpenMock
OpenMock is a Go service that can mock services in integration tests, staging environment, or anywhere.  The goal is to simplify the process of writing mocks in various channels.  Currently it supports three channels: HTTP Kafka AMQP (e.g. RabbitMQ) The admin API allows you to manipulate the mock behaviour provided by openmock, live.  The base path for the admin API is "/api/v1".



    Schemes:
      http
    Host: localhost
    BasePath: /api/v1
    Version: 0.2.0

    Consumes:
    - application/json
    - application/yaml

    Produces:
    - application/json
    - application/yaml

swagger:meta
*/
package restapi
